# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - '/root/agf-uploader:/app'
    command: /bin/sh -c "yarn && quasar dev"
